[theme]
primaryColor = "#0066ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[server]
port = 8501
headless = true
runOnSave = true
